package sy.model.base;
// Generated 2016-5-1 13:55:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name = "record", catalog = "sshe")
public class Record implements java.io.Serializable {

	private String id;
	private Activity activity;
	private ActivityUser activityUser;
	private String score;
	private Date createdatetime;
	
	public Record() {
	}

	public Record(String id) {
		this.id = id;
	}

	public Record(String id, Activity activity, ActivityUser activityUser,Date createdatetime, String score) {
		this.id = id;
		this.activity = activity;
		this.activityUser = activityUser;
		this.score = score;
		this.createdatetime = createdatetime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false,length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activityid")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public ActivityUser getActivityUser() {
		return this.activityUser;
	}

	public void setActivityUser(ActivityUser activityUser) {
		this.activityUser = activityUser;
	}

	@Column(name = "score", length = 50)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdatetime", length = 19)
	public Date getCreatedatetime() {
		if (this.createdatetime != null)
			return this.createdatetime;
		return new Date();
	}

	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}
}
